### ISSUE TITLE
Some people (higher ranked) don't have 2nd row of stats

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/tmio#103]
### Examples, No second row

* AR_Down: <https://trackmania.io/#/player/8f08302a-f670-463b-9f71-fbfacffb8bd1/cotd>
* Scrapie: <https://trackmania.io/#/player/scrapie/cotd>

![image](https://github.com/openplanet-nl/tmio/assets/1046448/ec1601c5-9477-45e1-bae8-e0d6e8412a8c)
![image](https://github.com/openplanet-nl/tmio/assets/1046448/d37b0b08-beaa-4304-be04-861596a0da86)

### how it should look

* XertroV: <https://trackmania.io/#/player/xertrov/cotd>

![image](https://github.com/openplanet-nl/tmio/assets/1046448/d4ad832f-3fc3-4945-89eb-4de1d3b05e20)

**Comment by XertroV** [comment]
hendo different again: <https://trackmania.io/#/player/0bd32607-2b58-4a9f-b213-0037322510c1/cotd>

![image](https://github.com/openplanet-nl/tmio/assets/1046448/25d609fc-26bc-4b1e-bc84-10a44e57f067)

**Comment by codecat** [comment]
This is intentional, but perhaps it would be nice to show the dates of "first div 1 win" etc.

**Comment by XertroV** [comment]
Well, AR_Down expressed disappointment the reset aren't shown for him.

**Comment by davidbmaier** [comment]
Just changed the way this works, the "best stats" sections should now always be shown for all players.
Additionally, the "Include reruns" checkbox determines if you see the main stats or the stats with reruns included (for some better consistency).
Hope that takes care of this issue.
