### ISSUE TITLE
Trophy ranking for a zone loads twice and loads the world zone first

### ISSUE THREAD

**Issue by nan-inf** [openplanet-nl/tmio#106]
When initially loading the trophy ranking for a specific zone (i.e., https://trackmania.io/#/top?zoneId=301f6188-7e13-11e8-8060-e284abfd2bc4), the API request for this zone is performed twice. It seems like this triggers a timing issue: either the page loads without issue (but the list does seem to be built twice), or the top 50 is shown twice. I can't exactly reproduce the first case with 100% success rate, but it seems like the second case always happens when I disable cache in the developer tools.

Duplicate requests:
![image](https://github.com/user-attachments/assets/34e92c54-9a84-4530-b9c2-13bb22f7f246)

Furthermore, initially loading the trophy ranking for a specific zone first loads the world ranking before switching to the zone-specific ranking.

(originally reported by Fractialia_/zouwu on Discord)

**Comment by davidbmaier** [comment]
Should be fixed, feel free to reopen if you can still reproduce it.
