### ISSUE TITLE
Migrate legacy competition features to newer comp page (and remove the legacy version)

### ISSUE THREAD

**Issue by Satamari** [openplanet-nl/tmio#108]
The text fields for individual races on competition pages [(example)](https://trackmania.io/#/competitions/616035) arent formatted quite right. Maybe the length and width got mixed up.
![imagen](https://github.com/user-attachments/assets/435eb875-7af7-4790-86bc-91d4e6d1979b)

**Comment by davidbmaier** [comment]
For reference: Instead of fixing the legacy page we should try to migrate its only exclusive feature (global leaderboards) to the newer competition page and get rid of the legacy version. Might also give us an opportunity to clean up the rounds visualization over there.

**Comment by davidbmaier** [comment]
Migration is complete, feel free to reopen if there are any features from the legacy page that you're missing on the new one.
