### ISSUE TITLE
Don't show "Jump to Record" button if rank greater than 10,000

### ISSUE THREAD

**Issue by chipsTM** [openplanet-nl/tmio#11]
Since we can only retrieve 10,000 records for leaderboards, clicking the "Jump to Record" button when you have a rank greater than 10,000 doesn't mean anything.

Suggestion is to either remove it or show a message saying that record cannot be shown due to it being greater than 10,000 records.
![image](https://user-images.githubusercontent.com/90581578/161605947-747a6f6c-2e23-472f-a8d9-268488f32663.png)

**Comment by codecat** [comment]
Will be fixed with the next site update!
