### ISSUE TITLE
Show appropiate error message when using invalid leaderboard UUID

### ISSUE THREAD

**Issue by Fort-TM** [openplanet-nl/tmio#110]
### Issue

When editing an URL and using an invalid leaderboard UUID, the site shows that I have a personal best on that map (despite me not having any runs on it) and will fall back to invalid values

![image](https://github.com/user-attachments/assets/9e0c092f-cc55-4a56-9222-1d39c008d249)

This issue was noticed when accessing [this link](https://trackmania.io/#/campaigns/leaderboard/f15771b1-53ff-4984-8d12-eb8ddd0167d7/VWkUUd1QAWVM4ohKzUiHFLX9jI3), which uses the official Summer 2024 campaign leaderboard UUID instead

### Expected behavior

The site should display an error message instead of such values.

**Comment by davidbmaier** [comment]
Should be fixed.

**Comment by Fort-TM** [comment]
Yup, shows "This leaderboard is empty." now. Thanks for the fix!
