### ISSUE TITLE
Disable button / link to tm.com for private activities

### ISSUE THREAD

**Issue by Fort-TM** [openplanet-nl/tmio#112]
## Issue

Private activities are not accessible by tm.io, since the internal account isn't a member of any clubs. As such, the site will display a notMember error (see #111), regardless of the club

## Suggestion

As explained by tooInfinite on Discord

> Might be worth checking if we can already see the private field from the club data, so we could disable the button or show some kind of info before you land on an error page

it would make sense to disable the button to access the activity, and maybe include a button to access it on https://www.trackmania.com/ instead (the latter would require logging in on tm.com to see the activity)

**Comment by davidbmaier** [comment]
Fixed, private campaigns should no longer be accessible via the UI.

**Comment by Fort-TM** [comment]
Confirmed fixed, private activities don't show any buttons now. Thanks👍
