### ISSUE TITLE
Trackmania.io icon font does not support the full range of Trackmania-supported icons

### ISSUE THREAD

**Issue by nan-inf** [openplanet-nl/tmio#113]
The icons supported in Trackmania (and, by extension, [Openplanet](https://openplanet.dev/docs/reference/icons)) extend beyond the icons included in `ForkAwesome`, the icon font used on trackmania.io; for instance, the Kenney game icons are not included in `ForkAwesome`. This means that any user-generated content using one of these icons is not correctly shown on trackmania.io due to missing glyphs.

For example, [my](https://trackmania.io/#/player/naninf) [club](https://trackmania.io/#/clubs/43550) tag:
![left: club tag rendered on trackmania.io, showing placeholders; right: club tag rendered in-game, showing the correct icons](https://github.com/user-attachments/assets/dccd9db0-6bc0-41c8-ac26-6f106e604355)
or [a map](https://trackmania.io/#/leaderboard/1sK9AOWHlGo6bm9qtpavIzv3mJ) using these icons:
![left: map name rendered on trackmania.io, showing placeholders; right: map name rendered in-game, showing the correct icons](https://github.com/user-attachments/assets/7c8dda61-ff7b-4a42-aa97-89c04e9c2042)
(note the first character in the map name is from the `ForkAwesome` icon set and thus renders correctly on trackmania.io, but the other four characters from the Kenney game icon set are not rendered correctly)

A simple fix would likely be to switch the icon font used on trackmania.io to the `ManiaIcons` font used on openplanet.dev, as this font does contain all icons supported in-game (for the [icons documentation page](https://openplanet.dev/docs/reference/icons)).

**Comment by codecat** [comment]
Indeed, we should switch to ManiaIcons. Should be a pretty easy fix.

**Comment by davidbmaier** [comment]
Should be fixed.
