### ISSUE TITLE
Hide Jump to record button for weekly shorts if PB is hidden/secret

### ISSUE THREAD

**Issue by Fort-TM** [openplanet-nl/tmio#118]
If you go to a Weekly Shorts map (e.g. [First](https://trackmania.io/#/campaigns/leaderboard/d8a5cde2-fbad-4eca-8845-e71664a4db6c/sSEx79xAXu4Azm8RqJ12VQnYfKd)) and click "Jump to record" for your PB, it will jump to the worst times in the map (or close to it, I think it's jumping to the map's player count position, which is 6389 at the moment)

**Comment by davidbmaier** [comment]
Should be fixed now, feel free to reopen if I've missed something.
