### ISSUE TITLE
Display record count for each map

### ISSUE THREAD

**Issue by davidbmaier** [openplanet-nl/tmio#12]
Using the `/api/token/leaderboard/group/.../map/.../surround/1/1` API with an absurdly high score, it's pretty easy to get the number of records on a map (exact if below 10k, rough estimate if above).
Could we integrate that in tm.io somehow? If you're concerned about extra requests, maybe only enable it for the seasonal campaign maps and give it a long cache? Or it could be a sponsor feature?

I'm mainly asking because I'm doing those requests pretty frequently for random people that don't know the API - and since it's just one request, tm.io would be able to handle it too.

**Comment by codecat** [comment]
Will add this! 👍

**Comment by codecat** [comment]
Will be added in the next update.
