### ISSUE TITLE
Campaign tracking - Add a boolean to tell if tracking is enabled

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/tmio#15]
Hi,

I'm working about adding campaign tracking on my library but not all campaigns are tracked, so it would be nice to add a boolean data to tell if WR tracking is enabled or not on it.

Also would be cool on the frontend so the "All record activity" button disappears if it's not enabled

**Comment by codecat** [comment]
Oops, I didn't realize the button was visible on non-tracked campaigns! I'll fix it 👍

**Comment by codecat** [comment]
This has been added. Note that the `tracked` boolean may be cached for up to an hour, which might matter if I add or remove tracking from a campaign.
