### ISSUE TITLE
3v3 recent matches list returns an empty array

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/tmio#2]
On the page https://trackmania.io/#/matches/3v3
The array on the "matches" key is empty, that results an empty page without any errors.

This is not the case for the Royal matches page https://trackmania.io/#/matches/royal
Here, the array is filled correctly

**Comment by codecat** [comment]
This is due to @jonese1234's API being slow, it ends up caching an empty array. I'll fix this by not caching when there's an error.
