### ISSUE TITLE
Mobile Site issues

### ISSUE THREAD

**Issue by bastiHST90** [openplanet-nl/tmio#21]
When on mobile I can't see the "info" button on this site

https://trackmania.io/#/rooms

And when in a room I can't see the action buttons (download and leaderboard)

It seems like I can't zoom out far enough to see everything the website has to offer.

I also tried using desktop view on chrome (android), but no dice.

Also: to get to my profile (upper right) I have to tilt the phone 90° to see my profile appear. (this 90° tilt doesn't work with the other issues i mentioned)

There might be more broken, idk.

**Comment by codecat** [comment]
This is mostly because on mobile there usually isn't enough space for all the columns, so it would have to be displayed in a different way.
