### ISSUE TITLE
[My Profile Page] Seems broken - Invalid account ID. even though i am logged in through Ubisoft API

### ISSUE THREAD

**Issue by w1lla** [openplanet-nl/tmio#26]
Hi, when i want to check out my profile page, it gives a player undefined as url when i logged in through the Trackmania/Ubisoft Connect API.
https://trackmania.io/#/player/undefined

https://trackmania.io/#/player/ab6fa572-48d7-4b16-a2d7-5c760a05f97b should be correct to show.

**Comment by codecat** [comment]
Can you try logging out and back in again please?

**Comment by w1lla** [comment]
Seems fixed now
