### ISSUE TITLE
Competition qualifier results can be descending (formatting issue)

### ISSUE THREAD

**Issue by KemTM** [openplanet-nl/tmio#27]
Seems like the current formatting assumes that the results are sorted in ascending order and pre-formats the deltas to have a plus sign in front of them. 
![image](https://user-images.githubusercontent.com/7620234/193475434-2091d2d7-f5d6-4fa6-8201-651d927aa6d7.png)
With the new competition tool this is no longer the case as it has three modes for aggregating the results:
* Sum of times (lower is better)
* Sum of Skill Points (higher is better)
* Sum of ranks (lower is better)

The Skill Point one is the one used in the image above.

**Comment by davidbmaier** [comment]
Should be fixed in the next update.
