### ISSUE TITLE
Accessibility issue on leaderboard page

### ISSUE THREAD

**Issue by byte-chan** [openplanet-nl/tmio#28]
With the new dark mode, the user's personal best rank has a contrast ratio of [2.35:1](https://webaim.org/resources/contrastchecker/?fcolor=2647D9&bcolor=1D1F20), making it nearly unreadable on some screens.
![personal best](https://user-images.githubusercontent.com/7152794/193475898-05b33b7c-098b-4948-b8e1-4468fce9bef3.png)
![WCAG](https://user-images.githubusercontent.com/7152794/193475907-27ae8302-5b82-47f4-9ca9-a622acc3f4e3.png)

**Comment by davidbmaier** [comment]
Fixed in the next update.
