### ISSUE TITLE
Player search is using an old name of players who have changed their name

### ISSUE THREAD

**Issue by Freeman999** [openplanet-nl/tmio#32]
I found a problem with the Playersearch, specifically with Users who have changed their names:
For example the Player "lxgend..." He changed this name to this several months ago. If I want to find him in the Playersearch I have to type his old name "lxgend-tm" which then gives me the entry for his profile. On his profile tho there is no indication that his name was "lxgend-tm", every mention is about his newest name "lxgend...".

I dont know how consistent this is, as it seems not to use the very first name of an account but also not necessarily the newest. Maybe it uses the name with with the player played TM the first time?

You guys are probably aware but I think its quite a inconvenience as more and more players will change their names over time.

For tesing purposes: The same issue arises with the player "xOETZIx" (old name "xLanzelord").

I think the best optimal solutions would be to have:
1. The old names of players listed on their profile.
2. The search function with both old and new names. It might be possible to have the "wrong" person show up when a Name is already taken again but that confusion would be not that severe as you could check previous names on their profile.

**Comment by codecat** [comment]
Hey, try it again now. I forgot I still had an offline database loaded locally.

**Comment by Freeman999** [comment]
Nop, not resolved. "lxgend..." still doesnt have any results while "lxgend-tm" has "lxgend..." as an result. Even with using an other broswer so its no cache problems or sth.

**Comment by codecat** [comment]
This seems fixed now, so I'll close this
