### ISSUE TITLE
never been 64th 

### ISSUE THREAD

**Issue by zentred** [openplanet-nl/tmio#34]
https://trackmania.io/#/player/6d683910-1917-4520-a295-0983f0758d35/cotd 

on my profile it says my best rank was 64th but i have pictures to show that it was atleast 71st - https://prnt.sc/K_kSRwTm1neg

also my pb hasnt changed since i got that time - https://prnt.sc/tS6YbF4tBtUR (picture taken right now)

**Comment by zentred** [comment]
also being 64th would have meant that i was div 1 not div 2 so that doesn't make sense anyway

**Comment by davidbmaier** [comment]
Should be fixed, feel free to reopen if there's some leftover problems that we missed.
