### ISSUE TITLE
Update outdated TMGL link

### ISSUE THREAD

**Issue by iwVerve** [openplanet-nl/tmio#45]
The TMGL badge (as seen on [CarlJr's profile](https://trackmania.io/#/player/carljr) for example) links to the dead `https://www.trackmania-grand-league.com/`, instead of the correct `https://www.trackmania.com/esports`.

**Comment by codecat** [comment]
Why the hell did Nadeo completely kill this domain name instead of redirect it!? Thanks for letting me know.. but I wonder what happens to all the sites linking to the old domain now, especially if the domain ever expires (it is set to expire on January 30th unless it's renewed.. 🤔)
