### ISSUE TITLE
Profile page: Club tag colors are inconsistent

### ISSUE THREAD

**Issue by davidbmaier** [openplanet-nl/tmio#5]
Club tag coloring is sometimes off because there's some logic to prevent low-contrast/bright colors, specifically in the header.
People expect their club tag colors to be the same as in-game and are therefore often surprised when that's not the case, claiming there's a bug.

It also seems to be displayed correctly in the tag components elsewhere on the page, leading to more confusing why the coloring is not consistent everywhere. See https://trackmania.io/#/player/c539f52e-dcb7-4e48-bcbf-bc37141a9520 for example (notice how the header's club colors are different from the ones in the "Club tag" field below).
This is especially confusing when the color gets _corrected_ in the middle of the tag or just for one or two characters.

If accessibility was the main concern, I'd say you're never going to find a perfect solution - people can always pick weird combinations of colors that don't really work in certain situations (incl. in-game). I think keeping the originally intended colors would make more sense since that's what basically all users expect already.

**Comment by codecat** [comment]
I fixed this today!
