### ISSUE TITLE
TM.io COTD Ranking Issue

### ISSUE THREAD

**Issue by MarsyJ3** [openplanet-nl/tmio#57]
![image](https://github.com/openplanet-nl/tmio/assets/135125841/96b59ed6-c18e-4a98-bd84-4ff8d24fc39f)
The second row. 103% doesn't sound right. I didn't even play the COTD.

**Comment by davidbmaier** [comment]
Should be fixed 👍

**Comment by MarsyJ3** [comment]
yeah all fixed
