### ISSUE TITLE
"Include reruns" excludes a main cup div win

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/tmio#59]
If I include reruns on my profile, my div win streak suddenly goes away:
![Screenshot 2023-06-02 133750](https://github.com/openplanet-nl/tmio/assets/37951898/9cbd704e-b3fc-4795-8283-701c6160016d)

Also this hover text for "Average div rank" should probably no longer say "includes reruns":
![Screenshot 2023-06-02 134116](https://github.com/openplanet-nl/tmio/assets/37951898/8ce5b015-3e3a-48fe-9029-c47acb7543ea)

**Comment by davidbmaier** [comment]
Fixed, thanks for the report 👍
