### ISSUE TITLE
Match: Older (7+ days) matches show generic error

### ISSUE THREAD

**Issue by davidbmaier** [openplanet-nl/tmio#6]
When trying to access matches that are not available anymore (older than seven days), the UI just shows a very generic error message that could be interpreted as a tm.io bug. See https://trackmania.io/#/match/LID-MTCH-b3agpuv3r0vkhdo for example.

Instead a simple message explaining possible reasons for the missing data (i.e. match data not being available after seven days) would already help people understand what's going on.

**Comment by codecat** [comment]
I fixed this today!

![image](https://user-images.githubusercontent.com/136534/160027083-1068ae52-205b-4485-b359-d91439c13453.png)
