### ISSUE TITLE
Off-by-one on TrackMania.io leaderboard when compared to ingame leaderboard

### ISSUE THREAD

**Issue by Atheuz** [openplanet-nl/tmio#67]
When playing TOTD today before the next COTD started, I noticed this:

On TrackMania.IO, on the leaderboard page for the TOTD (i.e. here: https://trackmania.io/#/totd/leaderboard/76c493e8-dfbf-4575-bb8a-62f4b14dd2e5/wCL3oeJm_XGQrZpo8H_1kxJa447)

![billede](https://github.com/openplanet-nl/tmio/assets/202696/1daa2cef-e3b2-40d1-83dd-c53d913fef1a)

And in game:
![billede](https://github.com/openplanet-nl/tmio/assets/202696/b6815449-a4ca-4894-985f-a74141bab6c6)

I.e., the problem is that ingame the record is 1321, and on TM.io the record is 1320.

I also saw this yesterday.

Is there something wrong or is TM.io just randomly off-by-one on multiple days? Usually you'd see a much wider discrepancy if TM.io was simply just not updated yet.

**Comment by codecat** [comment]
This might be hard to check for COTD, but is this still a problem? It could've just been a caching coincedence.

**Comment by davidbmaier** [comment]
Just checked on some older maps and can't reproduce it - could just be a caching issue where someone just overtook you and the game updated quicker while the tm.io data was still cached for a minute or so.
If you can consistently reproduce it on a map (without it resolving itself after a few minutes automatically), that's definitely worth investigating though.

**Comment by Atheuz** [comment]
Haven't noticed this lately, maybe Nadeo fixed it.

**Comment by Atheuz** [comment]
Will reopen if I see it again.

**Comment by Atheuz** [comment]
As tooInfinite explained it to me, paraphrased: The banner rank is an estimate, calculated by submitting your PB to an endpoint. This endpoint returns your would-be rank if you drove it now. However, because multiple people can have the same time, your would-be rank is the last in that list.

I.e. given these actual rankings:

| Rank | Player | Time   |
|------|--------|--------|
| 1000 | A      | 60.000 |
| 1001 | B      | 60.000 |
| 1002 | YOU    | 60.000 |
| 1003 | D      | 60.000 |
| 1004 | E      | 60.000 |

If you wanted your rank in the banner, you would get 1004 because of the 4 other players by querying the endpoint in question.

Note, that apparently tm.io subtracts 1 from the result which is why you would get 1004 and not 1005.

I'm happy with that explanation.
