### ISSUE TITLE
Trackmania Trophies System

### ISSUE THREAD

**Issue by Cacte-TM** [openplanet-nl/tmio#69]
It's not so much a problem as a suggestion. As you may know, Trackmania **trophies expire after 1 year**. They remain visible but are grayed out. Could you add an **all-time leaderboard** for trophies without taking this expiration into account? In addition, I think it would be nice to **have access to more than just the top 1000 world** for the trophy ranking (normal ranking and potentially all-time leaderboard)... Today, we can see the world's top 1000 in the trophy ranking, but not much more. Having access, for example, to the world top 5000 or 10000 could be really nice in my opinion!

I look forward to your feedback and thank you in advance!

**Comment by davidbmaier** [comment]
Thanks for the suggestions!

1. Calculating the all-time trophy points (including expired ones) for a single player requires going through the whole trophy history, which can easily translate to tens, even hundreds of requests against Nadeo's API. Of course it could be cached heavily, but the expectation would be - if the basic trophy count can be retrieved easily - that this all-time count would be similarly accurate.
So at the moment it doesn't look likely that we'll implement this unless we find a good alternative solution (and we find the time to implement it).
2. The current limit of 1,000 entries in the global trophy rankings still comes from a time where the underlying API was quite a bit slower - we think we should be able to increase that to 10,000, so we'll look into that soon. 👍

**Comment by Cacte-TM** [comment]
Hi,
Thanks for your answer.
Just a little question : Since expired trophies are already written in the "Trophy Gains" tab, wouldn't it be possible to simply add a button to add them. Without necessarily doing a ranking, I think that having the possibility of knowing our total score would be quite nice and, I think, quick to code...
What do you think and thanks in advance!
Have a nice day!

**Comment by davidbmaier** [comment]
Adding up all the expired trophy points still requires fetching the entire trophy history of the player. It still isn't really possible without spamming the API for that user's data.

Showing the total number of trophy points based on what the user has manually requested would just encourage people to perform the API spam we'd like to avoid in the first place, just with worse UX.

Nadeo specifically designed the trophy points to expire, so they have no incentive to give us an easy way to retrieve the data you're looking for that doesn't waste their resources - it might be easy to implement, but it's not something we'd like to make available on tm.io at the moment (also considering this has been the first time it's been requested afaik).
If retrieving this data becomes less spammy, or there's an alternative source we could use, we may reconsider it though.

**Comment by davidbmaier** [comment]
The trophies page has been adjusted to show the top 10,000 entries.
Calculating and displaying an all-time trophy value per player is not planned as discussed above - if there are ways to retrieve that information easily and without spamming Nadeo's API in the future, we can take another look.
