### ISSUE TITLE
Nonexistant player account causes other player names to not resolve

### ISSUE THREAD

**Issue by nan-inf** [openplanet-nl/tmio#74]
The `/api/map/{mapUid}` endpoint includes `authorplayer` and `submitterplayer` objects, containing information about respectively the author and submitter of the map. However, if the `authorplayer` has an account ID that does not resolve to a Ubisoft account, then the display name of the `submitterplayer` does not resolve correctly. Other entries, like `tag`, `zone`, and `meta`, do resolve correctly. Hence, the "submitter" row in the table on the map page correctly shows the country flag and the club tag, but no display name or link to their profile.

[This is an example of a map where this happens.](https://trackmania.io/#/leaderboard/jWfUsJlIrHATuidRtFNezCyh4oe) ([direct link to `/api/map/{mapUid}` endpoint](https://trackmania.io/api/map/jWfUsJlIrHATuidRtFNezCyh4oe))

Partial API output:

```json
{
  "authorplayer": {
    "name": "",
    "id": "3ba03d80-8c3e-41cb-b1ac-7694fa6fe2d1"
  },
  "submitterplayer": {
    "name": "",
    "tag": "$S$60FS$FFFPLIT",
    "id": "e8f35258-b507-487d-b470-52587d1445a6",
    "zone": {…},
    "meta": {…}
  },
  …
}
```

The expected output is "Denniss.." for `.submitterplayer.name`.

Note: the underlying reason for this map having an author with an invalid account ID is that they last saved the map while in offline mode, where the game assigns an arbitrary account ID. From my limited testing, it seems like this account ID is not the same for everyone in offline mode (here, the author's offline account ID is `3ba0…`, but if I start the game in offline mode, my account ID is `c91d…`), but is constant for a single client (mine stays the same after restarting Ubisoft Connect and my computer). Of course, this is very limited testing, so there might be something else governing the offline account ID.

There might also be another issue here in that the author is now not shown at all. I'm not sure what the best way to solve this would be; it is very likely impossible to correctly convert the offline account ID to the corresponding online account ID (which, in this case, is [`ed96…`](https://trackmania.io/#/player/ed96f75e-d80a-4066-9516-783541c2709c)). Some indicator of a nonexistant account could still be useful, though; currently the "author" row in the table is just empty, as well as the "by" text in the header of the page. For reference, trackmania.com "solves" this by [showing the full account ID](https://www.trackmania.com/tracks/jWfUsJlIrHATuidRtFNezCyh4oe) if a display name cannot be resolved.

**Comment by davidbmaier** [comment]
Should be fixed, accounts that don't exist should be shown as their IDs with a tooltip explaining what might have happened.
