### ISSUE TITLE
Advertisement image aspect ratio changed

### ISSUE THREAD

**Issue by nan-inf** [openplanet-nl/tmio#76]
The aspect ratio of the large images in advertisements has changed from 16 : 9 to 64 : 41 in [the Winter 2024 update.](https://www.trackmania.com/news/7901) However, [the advertisements page](https://trackmania.io/#/ads) of tm.io still shows the old ratio in the table header.

**Comment by davidbmaier** [comment]
Fixed, will be live after the next deployment.
