### ISSUE TITLE
64th place in COTD div marked as "unplayed"

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/tmio#78]
In div 1 in this cup (https://trackmania.io/#/cotd/13911), it seems all 64 people showed up and played, however for the person who got 64th (https://trackmania.io/#/player/00a8fa73-69fb-43c9-8fea-a9d4cee8de6c/cotd), it says on their profile they didn't play at all. Looking at div 2 for that same cup, there are 12 people who didn't play, and it shows their placement as `?` and score as `n/a`. From what I can gather on Nadeo's API, if someone didn't play, their rank and score are returned as null instead of a real value, so this should be properly reflected on the website. As a consequence to this, when querying TMIO's API, I get a divrank of 64 for cups in which I didn't play. I feel this should return 0 or -1 for placement instead.

**Comment by davidbmaier** [comment]
Good catch, tm.io is currently not differentiating correctly between 64th and unplayed - looking into it.

**Comment by davidbmaier** [comment]
Should now be fixed.
