### ISSUE TITLE
Exclude COTD reruns from table when "Include reruns" is unchecked

### ISSUE THREAD

**Issue by chrisdunnbirch** [openplanet-nl/tmio#83]
It is consistently confusing that reruns are included in the table of COTD results when the "Include reruns" checkbox is not checked at the top of the page.

I would personally prefer them to be hidden so that what you see in the table matches up with the stats you see in the header of the page.

> Just to clarify, the colors don't show your best division, it's just based on the div number.
> Div 1 is green, 2 is gold, 3 is silver, 4 is bronze, everything else is dark grey.
Not 100% intuitive though to be fair.
>
> Either way, the most obvious solution to the confusion is probably just to remove all rerun entries from the table if the checkbox is unchecked. Probably will require some thinking about whether the API will need to be adjusted as well (to prevent the "Load more" button from doing nothing if only reruns get loaded and none of them get shown).

_Originally posted by @davidbmaier in https://github.com/openplanet-nl/tmio/issues/66#issuecomment-1714400438_

**Comment by davidbmaier** [comment]
Fixed, the table data should now be consistent with the stats.
