### ISSUE TITLE
Top Players page not updated

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/tmio#85]
I can't say for sure when it was updated last, but the page says it's updated twice a day and it definitely hasn't been for at least a few days, probably weeks. For example, Scrapie on that page is about 7 million trophy points below where he actually is (based on his profile), and it seems he got those in the past 8 days or so. I'm also about 500,000 trophy points and 137 places behind where it says on my profile, and I got those trophies over the past few weeks.

**Comment by codecat** [comment]
@jonese1234 Is something going on with your server?

**Comment by jonese1234** [comment]
Ill take a look

**Comment by davidbmaier** [comment]
This seems to have been resolved, closing.
