### ISSUE TITLE
Reruns excluded from COTDs on profiles

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/tmio#86]
I saw some recent discussion about reruns, maybe it's now supposed to show them when `Include reruns` is checked but it's not working as expected?

I assume this change is from [277919a](https://github.com/codecat/trackmania.io/commit/277919add7a4c9e42c64603483aa06cb2a073441), but the repo is private so I can't say for sure. "Filter reruns from player COTDs based on query" does sound like the culprit but based on what query?

Reruns are also being excluded from the API.

**Comment by davidbmaier** [comment]
Can't reproduce your problem, see https://trackmania.io/#/player/e387f7d8-afb0-4bf6-bb29-868d1a62de3b/cotd for example.
By default reruns are excluded from the stats and the table, and they are included if you toggle the checkbox (which re-requests the COTD data with `includeReruns=true`).
If that doesn't work for you, try doing a full refresh in case you have an old version of the UI cached.

**Comment by ezio416** [comment]
Thanks, I must have had the old UI still cached, it's working today with the checkbox ticked. The API however is still returning only primary cups, I'm guessing I need to pass something else to it now to get reruns as well (passing `includeReruns` and `includeReruns=true` in the request url does not do it, and passing those as a param returns html instead of json data)

**Comment by davidbmaier** [comment]
I mean you can always just check what the UI requests via the browser's network tab.
`https://trackmania.io/api/player/e387f7d8-afb0-4bf6-bb29-868d1a62de3b/cotd/0?includeReruns=true` works fine to get reruns, do you have an example where it doesn't seem to work?

**Comment by ezio416** [comment]
Yeah I actually figured that out just one minute ago, I was doing stuff in the wrong order in my script. Thank you again!
