### ISSUE TITLE
Zones missing for some players in some places

### ISSUE THREAD

**Issue by nan-inf** [openplanet-nl/tmio#91]
On some pages (for example [TOTD](https://trackmania.io/#/totd) or [campaign leaderboards and world record history](https://trackmania.io/#/campaigns/0/57857)), zones aren't correctly shown for all players. For example, on the TOTD page, zones are shown for djabski and Voltus-, but not for SoulDrinker27 and Habe... The `zone` key also seems to be missing from the TM.io API response for these endpoints. Viewing a player's profile does correctly show their zone, though.

**Comment by codecat** [comment]
I've restarted the website which seemed to fix the missing flags from cache. Unsure what caused this though.

**Comment by davidbmaier** [comment]
Closing since it seems to just have been a temporary issue - feel free to reopen if you can reproduce it.
