### ISSUE TITLE
see top players per region

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/tmio#92]
I think it would be cool to be able to search for a region (or any sub-region) and see its top players instead of just those for World. I'm mainly asking because I'm 11th in my region and would like to see what I need to be 10th, and in this case, even just seeing the player's own region (or parents) would be nice too

**Comment by davidbmaier** [comment]
Not really data we can get dynamically from Nadeo, but maybe @jonese1234 could help with his data so we could add a zone selection to https://trackmania.io/#/top/trophies (even if it wouldn't be perfect, it should be pretty good for the top spots).

**Comment by codecat** [comment]
I still worry that people are going to then increasingly ask us to add a zone selector to other places where it's not going to be possible, as people are going to be confused by this inconsistency.

But in general, I am not against this, just a bit cautious.

**Comment by jonese1234** [comment]
Literally have a PR sitting for it that needs some more work if we want it its not that hard

**Comment by davidbmaier** [comment]
Implemented.
