### ISSUE TITLE
Tracks with 15 finishers lose Player Count when more records are loaded.

### ISSUE THREAD

**Issue by TNTreee** [openplanet-nl/tmio#95]
See images
![image](https://github.com/openplanet-nl/tmio/assets/118268880/e0215d65-d18d-4dbf-a467-d066211c503b)
![image](https://github.com/openplanet-nl/tmio/assets/118268880/eb3558a4-999b-4f4e-baeb-32cead8ea88e)
Happens on all maps with 15 finishers, would link to an example but would be invalid when another person finishes it.

**Comment by davidbmaier** [comment]
Should be fixed, feel free to reopen if you can still reproduce it somewhere.
